/* 
	All of the data used by the app
	All numbers are in millions, i.e. 10 native speakers = 10,000,000 native speakers
	Sources: *TODO*
*/
data = {
    "cmn": {
        "name": "Mandarin Chinese",
        "nat": "1082",
        "tot": "1120",
        "rank": "1",
        "greeting": "",
        "countries": {
            "CN": 1,
            "TW": 1,
            "SG": 1
        }
    },
    "eng": {
        "name": "English",
        "nat": "355",
        "tot": "554",
        "rank": "2",
        "greeting": "Hello friend",
        "countries": {
            "AG": 1,
            "AU": 1,
            "BS": 1,
            "BB": 1,
            "BZ": 1,
            "BW": 1,
            "CM": 1,
            "CA": 1,
            "CW": 1,
            "DM": 1,
            "ER": 1,
            "FJ": 1,
            "GM": 1,
            "GH": 1,
            "GD": 1,
            "GY": 1,
            "HK": 1,
            "IN": 1,
            "IE": 1,
            "JM": 1,
            "KE": 1,
            "KI": 1,
            "LS": 1,
            "LR": 1,
            "MW": 1,
            "MY": 1,
            "MT": 1,
            "MH": 1,
            "MU": 1,
            "FM": 1,
            "NA": 1,
            "NR": 1,
            "NZ": 1,
            "NG": 1,
            "PK": 1,
            "PW": 1,
            "PG": 1,
            "PH": 1,
            "RW": 1,
            "KN": 1,
            "LC": 1,
            "VC": 1,
            "WS": 1,
            "SC": 1,
            "SL": 1,
            "SG": 1,
            "SX": 1,
            "SB": 1,
            "SO": 1,
            "ZA": 1,
            "SS": 1,
            "LK": 1,
            "SD": 1,
            "SZ": 1,
            "TZ": 1,
            "TO": 1,
            "TT": 1,
            "TV": 1,
            "UG": 1,
            "GB": 1,
            "US": 1,
            "VU": 1,
            "ZM": 1,
            "ZW": 1
        }
    },
    "ita": {
        "name": "Italian",
        "nat": "73",
        "tot": "115",
        "rank": "12",
        "greeting": "Ciao amico",
        "countries": {
            "IT": 1,
            "HR": 1,
            "SM": 1,
            "SI": 1,
            "CH": 1,
            "VA": 1
        }
    },
};